apiVersion: v1
kind: Service
metadata:
  name: basketapi
  labels:
    app: basketapi
spec:
  selector:
    app: basketapi
  type: LoadBalancer
  ports:
    - name: "3502"
      port: 3502
      targetPort: 80
