#DONT THINK THIS IS ANYWAY CORRECT!
apiVersion: v1
kind: Pod
metadata:
  name: basketdb
  labels:
    app: basketdb

spec:
  containers:
    - image: redis:alpine
      name: basketdb
      ports:
        - containerPort: 6379
      resources: {}
      volumeMounts:
        - mountPath: /data/basketdb
          name: basketredisdata
  restartPolicy: Never #Always
  volumes:
    - name: basketredisdata
      persistentVolumeClaim:
        claimName: basketredisdata
status: {}
