apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basketredisdata
  labels:
    app: basketredisdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
