apiVersion: v1
kind: Service
metadata:
  name: basketdb-service
spec:
  selector:
    app: basketdb-pod
  type: NodePort
  ports:
    - name: "redisbaby"
      port: 6379
      targetPort: 6379
      nodePort: 30003
