apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basket_redis_data
  labels:
    app: basket_redis_data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
