apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basket_api_claim0
  labels:
    app: basket_api_claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
