apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basketapiclaim0
  labels:
    app: basketapiclaim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
