apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketapi-pod
  template:
    metadata:
      labels:
        app: basketapi-pod
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
          image: marcusquigley/basketapi:1.1
          name: basketapi-container
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 3
            exec:
              command:
                - cat
                - healthfile
          livenessProbe:
            httpGet:
              path: /liveness
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10

      restartPolicy: Always
