apiVersion: v1
kind: Service
metadata:
  name: basketapi-service
spec:
  selector:
    app: basketapi-pod
  type: NodePort
  ports:
    - name: "bingo2"
      port: 14002
      targetPort: 80
      nodePort: 30006
