apiVersion: v1
kind: Service
metadata:
  name: basket_api
  labels:
    app: basket_api
spec:
  selector:
    app: basket_api
  type: LoadBalancer
  ports:
    - name: "3502"
      port: 3502
      targetPort: 80
