apiVersion: v1
kind: Service
metadata:
  name: catalogapi
  labels:
    app: catalogapi
spec:
  selector:
    app: catalogapi
  type: LoadBalancer
  ports:
    - name: "3500"
      port: 3500
      targetPort: 80
