apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalogapiclaim0
  labels:
    app: catalogapiclaim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
