apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog_postgres_data
  labels:
    app: catalog_postgres_data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
