apiVersion: v1
kind: Pod
metadata:
  name: catalogdb
  labels:
    app: catalogdb
spec:
  containers:
    - env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: marcus
      image: postgres:alpine
      name: catalogdb
      ports:
        - containerPort: 5432
      resources: {}
      volumeMounts:
        - mountPath: /data/catalogdb
          name: catalogpostgresdata
  restartPolicy: Always
  volumes:
    - name: catalogpostgresdata
      persistentVolumeClaim:
        claimName: catalogpostgresdata
status: {}
