apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
spec:
  selector:
    app: catalogapi-pod
  type: NodePort
  ports:
    - name: "bingo"
      port: 14000
      targetPort: 80
      nodePort: 30005
