apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalogpostgresdata
  labels:
    app: catalogpostgresdata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
