apiVersion: v1
kind: Service
metadata:
  name: catalogdb
  labels:
    app: catalogdb
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: catalogdb
status:
  loadBalancer: {}
