apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: node-env
  name: env-vars
data:
  ASPNETCORE_ENVIRONMENT: Development
  POSTGRES_SERVER: "catalogdb"
  POSTGRES_DB: "discountdb"
  POSTGRES_USER: "marcus"
  POSTGRES_PORT: "5432"
  POSTGRES_PASSWORD: "password"
  IdentityUri: "https://identityservice/"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discountgrpc
  labels:
    app: discountgrpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discountgrpc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: discountgrpc
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ASPNETCORE_ENVIRONMENT
                  name: env-vars
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env-vars
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: env-vars
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: env-vars
            - name: POSTGRES_SERVER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_SERVER
                  name: env-vars
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: env-vars
            - name: IdentityUri
              valueFrom:
                configMapKeyRef:
                  key: IdentityUri
                  name: env-vars
          image: discountgrpc
          name: discountgrpc
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /discountgrpcwork/
              name: discountgrpcclaim0
      restartPolicy: Never #Always
      volumes:
        - name: discountgrpcclaim0
          persistentVolumeClaim:
            claimName: discountgrpcclaim0
status: {}
