apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discountgrpcclaim0
  labels:
    app: discountgrpcclaim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
