apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: node-env
  name: env-vars
data:
  ASPNETCORE_ENVIRONMENT: Local
  FrontEndUri: mvc_frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity_service
  labels:
    app: identity_service
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity_service
      version: "1.0"

  template:
    metadata:
      labels:
        app: identity_service
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ASPNETCORE_ENVIRONMENT
                  name: env-vars
          image: identity_service
          name: identity_service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
