apiVersion: v1
kind: Service
metadata:
  name: identityservice
  labels:
    app: identityservice
spec:
  ports:
    - name: "8010"
      port: 8010
      targetPort: 80
  selector:
    app: identityservice
status:
  loadBalancer: {}
