apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: node-env
  name: env-vars
data:
  ASPNETCORE_ENVIRONMENT: Local
  FrontEndUri: mvcfrontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityservice
  labels:
    app: identityservice
    # version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityservice
      # version: "1.0"

  template:
    metadata:
      labels:
        app: identityservice
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ASPNETCORE_ENVIRONMENT
                  name: env-vars
          image: identityservice
          name: identityservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
