apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mvcfrontendclaim0
  labels:
    app: mvcfrontendclaim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
