apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mvcfrontendclaim1
  labels:
    app: mvcfrontendclaim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
