apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mvc_frontend_claim1
  labels:
    app: mvc_frontend_claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
