apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvcfrontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvcfrontend-pod
  template:
    metadata:
      labels:
        app: mvcfrontend-pod
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
          image: marcusquigley/mvcfrontend:1.0
          name: mvcfrontend-container
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
