apiVersion: v1
kind: Service
metadata:
  name: ocelotapi
  labels:
    app: ocelotapi
spec:
  ports:
    - name: "8010"
      port: 8010
      targetPort: 80
  selector:
    app: ocelotapi
status:
  loadBalancer: {}
