apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: node-env
  name: env-vars
data:
  ASPNETCORE_ENVIRONMENT: Docked
  IdentityUri: "https://identityservice/"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotapi
  labels:
    app: ocelotapi
    # version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocelotapi
      # version: "1.0"

  template:
    metadata:
      labels:
        app: ocelotapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ASPNETCORE_ENVIRONMENT
                  name: env-vars
            - name: IdentityUri
              valueFrom:
                configMapKeyRef:
                  key: IdentityUri
                  name: env-vars
          image: ocelotapi
          name: ocelotapi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Never #Always
