apiVersion: v1
kind: Service
metadata:
  name: orderapi-service
spec:
  selector:
    app: orderapi-pod
  type: NodePort
  ports:
    - name: "bingo3"
      port: 14004
      targetPort: 80
      nodePort: 30007
