apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ordermongodata
  labels:
    app: ordermongodata
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
