apiVersion: v1
kind: Service
metadata:
  name: orderdb-service
spec:
  selector:
    app: orderdb-pod
  type: NodePort
  ports:
    - name: "mongobaby"
      port: 27017
      targetPort: 27017
      nodePort: 30004
