apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order_api_claim0
  labels:
    app: order_api_claim0

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
