apiVersion: v1
kind: Service
metadata:
  name: orderdb
  labels:
    app: orderdb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    app: orderdb
status:
  loadBalancer: {}
