apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderapiclaim0
  labels:
    app: orderapiclaim0

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
