apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: orderapi-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orderapi-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 65
