apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order_mongo_data
  labels:
    app: order_mongo_data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
