apiVersion: v1
kind: Service
metadata:
  name: orderapi
  labels:
    app: orderapi

spec:
  selector:
    app: orderapi
    type: LoadBalancer
  ports:
    - name: "3508"
      port: 3508
      targetPort: 80
