# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: rabbitmq-deployment
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: rabbitmq-pod
#   template:
#     metadata:
#       labels:
#         app: rabbitmq-pod
#     spec:
#       containers:
#         - image: rabbitmq
#           name: rabbitmq-container
#           ports:
#             - containerPort: 15672
#             - containerPort: 5672
#           resources:
#             limits:
#               memory: "128Mi"
#               cpu: "500m"
#       restartPolicy: Always
