apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  containers:
    - image: rabbitmq:3-management-alpine
      name: rabbitmq
      ports:
        - containerPort: 5672
        - containerPort: 15672
      resources: {}
  restartPolicy: Never #Always
status: {}
