apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq-pod
  ports:
    - name: "http-admin"
      port: 15672
      targetPort: 15672
      nodePort: 30001
    - name: "data"
      port: 5672
      targetPort: 5672

  type: LoadBalancer
