apiVersion: v1
kind: Service
metadata:
  name: apigateway-service
spec:
  selector:
    app: apigateway-pod
  ports:
    - name: "bingo4"
      port: 14006
      targetPort: 80
      protocol: TCP
  #type: LoadBalancer
