apiVersion: v1
kind: Service
metadata:
  name: catalogdb-service
spec:
  selector:
    app: catalogdb-pod
  ports:
    - name: "postgresbaby"
      port: 5432
      targetPort: 5432
      protocol: TCP
