apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Code\tools\kompose.exe convert -o ./k8s
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: basket-api
  name: basket-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: basket-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Code\tools\kompose.exe convert -o ./k8s
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: basket-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: BasketUpdatedQueue
              value: basketinventoryupdated-queue
            - name: EventBusAddress
              value: amqp://guest:guest@rabbitmq:5672
            - name: RedisServerUrl
              value: basketdb
            - name: grpcServiceUrl
              value: http://discount_grpc:80
          image: basket-api
          name: basket-api
          ports:
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /basketwork/Services/Basket/Basket.Api/
              name: basket-api-claim0
      restartPolicy: Always
      volumes:
        - name: basket-api-claim0
          persistentVolumeClaim:
            claimName: basket-api-claim0
status: {}
