apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Code\tools\kompose.exe convert -o ./k8s
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: catalog-api
  name: catalog-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalog-api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Code\tools\kompose.exe convert -o ./k8s
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: catalog-api
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: EventBusAddress
              value: amqp://guest:guest@rabbitmq:5672
            - name: InventoryUpdatedQueue
              value: inventoryupdated-queue
            - name: OutOfStockQueue
              value: outofstock-queue
            - name: POSTGRES_DB
              value: catalogdb
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_SERVER
              value: catalogdb
            - name: POSTGRES_USER
              value: marcus
          image: catalog-api
          name: catalog-api
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /work/Services/Catalog/Catalog.Api/
              name: catalog-api-claim0
      restartPolicy: Always
      volumes:
        - name: catalog-api-claim0
          persistentVolumeClaim:
            claimName: catalog-api-claim0
status: {}
