apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Code\tools\kompose.exe convert -o ./k8s
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: catalog-api
  name: catalog_api
spec:
  ports:
    - name: "3500"
      port: 3500
      targetPort: 80
  selector:
    io.kompose.service: catalog-api
status:
  loadBalancer: {}
