apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\Code\tools\kompose.exe convert -o ./k8s
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: catalogdb
  name: catalogdb
spec:
  containers:
    - env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: marcus
      image: postgres:alpine
      name: catalogdb
      ports:
        - containerPort: 5432
      resources: {}
      volumeMounts:
        - mountPath: /data/catalogdb
          name: catalog-postgres-data
  restartPolicy: Never
  volumes:
    - name: catalog-postgres-data
      persistentVolumeClaim:
        claimName: catalog-postgres-data
status: {}
