apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Code\tools\kompose.exe convert -o ./k8s
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ocelot-api
  name: ocelot_api
spec:
  ports:
    - name: "8010"
      port: 8010
      targetPort: 80
  selector:
    io.kompose.service: ocelot-api
status:
  loadBalancer: {}
