apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: apigateway-pod
  template:
    metadata:
      labels:
        app: apigateway-pod
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
          image: {{ .Values.apigateway.image }}:{{ .Values.version }}
          name: apigateway-container
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
