apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi-deployment
spec:
  replicas:  {{ .Values.replicas }}
  selector:
    matchLabels:
      app: basketapi-pod
  template:
    metadata:
      labels:
        app: basketapi-pod
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
          image: {{ .Values.basket.image }}:{{ .Values.version }}
          name: basketapi-container
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
