apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb-deployment
spec:
  replicas:  {{ .Values.replicas }}
  selector:
    matchLabels:
      app: catalogdb-pod
  template:
    metadata:
      labels:
        app: catalogdb-pod
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: marcus
          image: postgres:alpine
          name: catalogdb-container
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /data/catalogdb
              name: catalogdata
      restartPolicy: Always
      volumes:
        - name: catalogdata
          persistentVolumeClaim:
            claimName: catalogdata-claim
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: catalogdata-claim
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 100Mi
# status: {}
