apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogapi-deployment
spec:
  replicas:  {{ .Values.replicas }}
  selector:
    matchLabels:
      app: catalogapi-pod
  template:
    metadata:
      labels:
        app: catalogapi-pod
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Kubernetes
          image: {{ .Values.catalog.image }}:{{ .Values.version }}
          name: catalogapi-container
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
      restartPolicy: Always
