version: '3.4'

services: 
  postgres_turk_db:
    image: postgres
    environment: 
      #POSTGRES_DB: "turkish_catalog"
      POSTGRES_USER: "fucker"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 5432:5432
  category_api:
    build: ./Services/Catalog/Catalog.Api/.
    environment: 
      POSTGRES_SERVER: "postgres_turk_db"
    ports: 
      - 3500:3000
    depends_on: 
      - postgres_turk_db


