version: '3.4'

services: 
  postgres_db:
    image: postgres:alpine
    environment: 
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 5432:5432
    # volumes:
    #   - truck-postgresdata:/var/lib/postgresql/data
  
  orderdb:
    image: mongo
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
   
  basket_redis_db:
    image: redis:alpine
    restart: always
    #environment: 
    ports:
      - 6379:6379
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: always
    environment: 
      teds: ""
    ports:
      - "5672:5672"
      - "15672:15672"


  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment: 
  #     #POSTGRES_DB: ""
  #     PGADMIN_DEFAULT_EMAIL: "admin@turkish.com"
  #     PGADMIN_DEFAULT_PASSWORD: "password"
  #   ports: 
  #     - 5050:80
  #   volumes:
  #     - pgadmin_data:/root/.pgadmin

  # portainer:
  #   image: portainer/portainer-ce
  #   container_name: portainer
  #   ports:
  #     - 8080:8000
  #     - 8090:9000
  #   volumes: 
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

  catalog_api:
    container_name: catalog_api
    build: 
      context: ./Services/Catalog/Catalog.Api
      target: debug
    environment: 
      POSTGRES_SERVER: "postgres_db"
      POSTGRES_DB: "catalogdb"
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 3500:4400
    volumes:
      - ./Services/Catalog/Catalog.Api/:/work/
    depends_on: 
      - postgres_db
   
  basket_api:
    container_name: basket_api
    build: 
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
      target: debug
    environment: 
      REDIS_SERVER: "basket_redis_db"
      grpcServiceUrl: "http://discount_grpc:4404"
      EventBusAddress: "amqp://guest:guest@rabbitmq:5672"
    ports: 
      - 3502:4402
    volumes:
      - ./Services/Basket/Basket.Api/:/basketwork/Services/Basket/Basket.Api/
    depends_on: 
      - basket_redis_db
      - rabbitmq

  discount_grpc:
    container_name: discount_grpc
    build: 
      context: ./Services/Discount/Discount.Grpc
      target: debug
    environment: 
      POSTGRES_SERVER: "postgres_db"
      POSTGRES_DB: "discountdb"
      POSTGRES_USER: "marcus"
      POSTGRES_PORT: "5432"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 3506:4404
    volumes:
      - ./Services/Discount/Discount.Grpc/:/discountgrpcwork/
    depends_on: 
      - postgres_db

  order_api:
    container_name: order_api
    build: 
      context: .
      dockerfile: Services/Orders/Orders.Api/Dockerfile
      target: debug
    environment: 
      POSTGRES_SERVER: "postgres_db"
      POSTGRES_DB: "orderdb"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
      EventBusAddress: "amqp://guest:guest@rabbitmq:5672"
      BasketCheckoutQueue: "basketcheckout-queue"
      MONGO_SERVER: "orderdb"
      MONGO_PORT: "27017"
      MONGO_DB: "OrderDb"
      MONGO_COLLECTION: "Orders"
    ports: 
      - 3508:4406
    volumes:
      - ./Services/Orders/Orders.Api/:/orderapiwork/Services/Orders/Orders.Api/
    depends_on: 
      - postgres_db 
      - rabbitmq
      - orderdb

  # border_api:
  #   container_name: border_api
  #   build: 
  #     context: .
  #     dockerfile: Services/Borders/Borders.Api/Dockerfile
  #     target: debug
  #   environment: 
     
  #     EventBusAddress: "amqp://guest:guest@rabbitmq:5672"
  #     BasketCheckoutQueue: "basketcheckout-queue"
     
  #   ports: 
  #     - 3508:4406
  #   # volumes:
  #   #   - ./Services/Orders/Orders.Api/:/orderapiwork/Services/Orders/Orders.Api/
  #   depends_on: 
  #     - rabbitmq


volumes: 
  mongo_data:
#   #truck-postgresdata:
#   #catalogapi_data:
#   #orderapi_data:
#   portainer_data:
#   #pgadmin_data:


