# docker build -t temp_catalog_api -f services/catalog/catalog.api/Dockerfile .  THis creates an image from the src dir...
version: '3.4'

services:
  catalogdb:
    image: postgres:alpine
    restart: "no"
    environment:
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports:
      - 5432:5432
    volumes:
      - catalog_postgres_data:/data/catalogdb

  orderdb:
    image: mongo
    restart: "no"
    ports:
      - "27017:27017"
    volumes:
      - order_mongo_data:/data/orderdb
    logging:
      # turns off logging
      driver: none

  basketdb:
    image: redis:alpine
    restart: "no"
    ports:
      - "6379:6379"
    volumes:
      - basket_redis_data:/data/basketdb

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    restart: "no"
    environment:
      teds: ""
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      # turns off logging
      driver: none

  catalog_api:
    container_name: catalog_api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile
      target: debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      POSTGRES_SERVER: "catalogdb"
      POSTGRES_DB: "catalogdb"
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
      EventBusAddress: "amqp://guest:guest@rabbitmq:5672"
      OutOfStockQueue: "outofstock-queue"
      InventoryUpdatedQueue: "inventoryupdated-queue"
      IdentityUri: "https://identity_service/"
    ports:
      - 3500:80
    volumes:
      - ./Services/Catalog/Catalog.Api/:/work/Services/Catalog/Catalog.Api/
    depends_on:
      - catalogdb

  basket_api:
    container_name: basket_api
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile
      target: debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      grpcServiceUrl: "http://discount_grpc:80"
      EventBusAddress: "amqp://guest:guest@rabbitmq:5672"
      BasketUpdatedQueue: "basketinventoryupdated-queue"
      RedisServerUrl: "basketdb"
      IdentityUri: "https://identity_service/"
    ports:
      - 3502:443
    volumes:
      - ./Services/Basket/Basket.Api/:/basketwork/Services/Basket/Basket.Api/
    depends_on:
      - basketdb #basket_redis_db
      - rabbitmq

  order_api:
    container_name: order_api
    build:
      context: .
      dockerfile: Services/Orders/Orders.Api/Dockerfile
      target: debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventBusAddress: "amqp://guest:guest@rabbitmq:5672"
      BasketCheckoutQueue: "basketcheckout-queue"
      MONGO_SERVER: "orderdb"
      MONGO_PORT: "27017"
      MONGO_DB: "OrderDb"
      MONGO_COLLECTION: "Orders"
      IdentityUri: "https://identity_service/"
    ports:
      - 3508:80
    volumes:
      - ./Services/Orders/Orders.Api/:/orderapiwork/Services/Orders/Orders.Api/
    depends_on:
      #- catalogdb 
      - rabbitmq
      - orderdb

  mvc_frontend:
    container_name: mvc_frontend
    build:
      context: .
      dockerfile: Frontends/Mvc/Web/Dockerfile
      target: debug
    environment:
      TruckCatalogUri: "http://ocelot_api/trucks/"
      BasketUri: "http://ocelot_api/basket/"
      OrdersUri: "http://ocelot_api/orders/"
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8001"
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUri: "https://identity_service/"
    ports:
      - "8000:80"
      - "8001:443"
      # volumes:
      #   - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      #   - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    depends_on:
      - catalog_api
      - order_api
      - basket_api
      - ocelot_api

  ocelot_api:
    container_name: ocelot_api
    build:
      context: .
      dockerfile: ApiGateways/OcelotApi/Dockerfile
      target: debug
    environment:
      ASPNETCORE_ENVIRONMENT: Docked
      IdentityUri: "https://identity_service/"
    ports:
      - 8010:80
    depends_on:
      - catalog_api
      - order_api
      - basket_api

  identity_service:
    container_name: identity_service
    build:
      context: .
      dockerfile: Security/Identity/Dockerfile
      target: debug
    environment:
      ASPNETCORE_ENVIRONMENT: Local
      FrontEndUri: mvc_frontend
    ports:
      - 3520:80

volumes:
  order_mongo_data:
    name: order_mongo_data
  basket_redis_data:
    name: basket_redis_data
  catalog_postgres_data:
    name: catalog_postgres_data
