version: '3.4'

services: 
  catalog_postgres_db:
    image: postgres:alpine
    environment: 
      POSTGRES_DB: "hess_catalog_db"
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 5432:5432
    volumes:
      - catalogapi_data:/var/lib/postgresql/data
  
  basket_redis_db:
    image: redis:alpine
    #environment: 
    ports:
      - 6379:6379

  discount_postgres_db:
    #container_name: discountdb
    #restart: always
    image: postgres:alpine
    environment: 
      POSTGRES_DB: "DiscountDb"
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 5431:5432
    volumes:
      - discountapi_data:/var/lib/postgresql/discountdata/

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment: 
  #     #POSTGRES_DB: ""
  #     PGADMIN_DEFAULT_EMAIL: "admin@turkish.com"
  #     PGADMIN_DEFAULT_PASSWORD: "password"
  #   ports: 
  #     - 5050:80
  #   volumes:
  #     - pgadmin_data:/root/.pgadmin

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - 8080:8000
      - 8090:9000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  catalog_api:
    container_name: catalog_api
    build: 
      context: ./Services/Catalog/Catalog.Api
      target: debug
    environment: 
      POSTGRES_SERVER: "catalog_postgres_db"
      POSTGRES_DB: "hess_catalog_db"
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 3500:4400
    volumes:
      - ./Services/Catalog/Catalog.Api/:/work/
    depends_on: 
      - catalog_postgres_db

 
  
  basket_api:
    container_name: basket_api
    build: 
      context: ./Services/Basket/Basket.Api
      target: debug
    environment: 
      REDIS_SERVER: "basket_redis_db"
    ports: 
      - 3502:4402
    volumes:
      - ./Services/Basket/Basket.Api/:/basketwork/
    depends_on: 
      - basket_redis_db

  discount_api:
    container_name: discount_api
    build: 
      context: ./Services/Discount/Discount.Api
      target: debug
    environment: 
      POSTGRES_SERVER: "discount_postgres_db"
      POSTGRES_DB: "DiscountDb"
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 3504:4404
    volumes:
      - ./Services/Discount/Discount.Api/:/discountwork1/
    depends_on: 
      - discount_postgres_db

volumes: 
  catalogapi_data:
  discountapi_data:
  portainer_data:
  #pgadmin_data:


