version: '3.4'

services: 
  postgres_turk_db:
    image: postgres
    environment: 
      #POSTGRES_DB: "turkish_catalog"
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 5432:5432
    volumes:
      - catalogapi_data:/data/db
  redis_db:
    image: redis:alpine
    #environment: 
    ports:
      - 6379:6379

  category_api:
    container_name: category_api
    build: 
      context: ./Services/Catalog/Catalog.Api
      target: debug
    environment: 
      POSTGRES_SERVER: "postgres_turk_db"
    ports: 
      - 3500:4400
    volumes:
      - ./Services/Catalog/Catalog.Api/:/work/
    depends_on: 
      - postgres_turk_db
  
  basket_api:
    container_name: basket_api
    build: 
      context: ./Services/Basket/Basket.Api
      target: debug
    environment: 
      REDIS_SERVER: "redis_db"
    ports: 
      - 3502:4402
    volumes:
      - ./Services/Basket/Basket.Api/:/basketwork/
    depends_on: 
      - redis_db

volumes: 
  catalogapi_data:


