version: '3.4'

services: 
  postgres_db:
    image: postgres:alpine
    environment: 
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 5432:5432
    # volumes:
    #   - truck-postgresdata:/var/lib/postgresql/data
   
  basket_redis_db:
    image: redis:alpine
    #environment: 
    ports:
      - 6379:6379
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    environment: 
      teds: ""
    ports:
      - 5672:5672
      - 15672:15672 #dashboard


  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment: 
  #     #POSTGRES_DB: ""
  #     PGADMIN_DEFAULT_EMAIL: "admin@turkish.com"
  #     PGADMIN_DEFAULT_PASSWORD: "password"
  #   ports: 
  #     - 5050:80
  #   volumes:
  #     - pgadmin_data:/root/.pgadmin

  # portainer:
  #   image: portainer/portainer-ce
  #   container_name: portainer
  #   ports:
  #     - 8080:8000
  #     - 8090:9000
  #   volumes: 
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - portainer_data:/data

  catalog_api:
    container_name: catalog_api
    build: 
      context: ./Services/Catalog/Catalog.Api
      target: debug
    environment: 
      POSTGRES_SERVER: "postgres_db"
      POSTGRES_DB: "catalogdb"
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 3500:4400
    volumes:
      - ./Services/Catalog/Catalog.Api/:/work/
    depends_on: 
      - postgres_db
   
  basket_api:
    container_name: basket_api
    build: 
      context: ./Services/Basket/Basket.Api
      target: debug
    environment: 
      REDIS_SERVER: "basket_redis_db"
      grpcServiceUrl: http://discount_grpc:4404
      #grpcServiceUrl: discount_grpc
    ports: 
      - 3502:4402
    volumes:
      - ./Services/Basket/Basket.Api/:/basketwork/
    depends_on: 
      - basket_redis_db

  discount_grpc:
    container_name: discount_grpc
    build: 
      context: ./Services/Discount/Discount.Grpc
      target: debug
    environment: 
      POSTGRES_SERVER: "postgres_db"
      POSTGRES_DB: "discountdb"
      POSTGRES_USER: "marcus"
      POSTGRES_PORT: "5432"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 3506:4404
    volumes:
      - ./Services/Discount/Discount.Grpc/:/discountgrpcwork/
    depends_on: 
      - postgres_db

  order_api:
    container_name: order_api
    build: 
      context: ./Services/Orders/Orders.Api
      target: debug
    environment: 
      POSTGRES_SERVER: "postgres_db"
      POSTGRES_DB: "orderdb"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 3508:4406
    volumes:
      - ./Services/Orders/Orders.Api/:/orderapiwork_boom/
    depends_on: 
      - postgres_db 

# volumes: 
#   #truck-postgresdata:
#   #catalogapi_data:
#   #discountapi_data:
#   #orderapi_data:
#   portainer_data:
#   #pgadmin_data:


