version: '3.4'

services: 
  catalog_postgres_db:
    image: postgres
    environment: 
      #POSTGRES_DB: "turkish_catalog"
      POSTGRES_USER: "marcus"
      POSTGRES_PASSWORD: "password"
    ports: 
      - 5432:5432
    volumes:
      - catalogapi_data:/data/db
  basket_redis_db:
    image: redis:alpine
    #environment: 
    ports:
      - 6379:6379
  
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - 8080:8000
      - 8090:9000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    

  catalog_api:
    container_name: catalog_api
    build: 
      context: ./Services/Catalog/Catalog.Api
      target: debug
    environment: 
      POSTGRES_SERVER: "catalog_postgres_db"
    ports: 
      - 3500:4400
    volumes:
      - ./Services/Catalog/Catalog.Api/:/work/
    depends_on: 
      - catalog_postgres_db
  
  basket_api:
    container_name: basket_api
    build: 
      context: ./Services/Basket/Basket.Api
      target: debug
    environment: 
      REDIS_SERVER: "basket_redis_db"
    ports: 
      - 3502:4402
    volumes:
      - ./Services/Basket/Basket.Api/:/basketwork/
    depends_on: 
      - basket_redis_db

volumes: 
  catalogapi_data:
  portainer_data:


