FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS debug
ENV ASPNETCORE_URLS=http://+:80  
#ENV ASPNETCORE_URLS=https://+:443  
RUN apt-get update
RUN apt-get install -y unzip
# dls a sh script from ../getvsdbgsh and pipes it to /bin/sh for execution and provides a few arguments, most importantly the /vsdbg which is where the remote debugger will be extracted to
RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l ~/vsdbg


WORKDIR /identitywork
COPY ["Security/Identity/Identity.csproj", "Security/Identity/"]

RUN dotnet restore "Security/Identity/Identity.csproj"

COPY . ./
RUN dotnet publish Security/Identity/Identity.csproj --no-restore -o out -c Release
#--no-launch-profile means it doesnt access launchSettings.json
ENTRYPOINT ["dotnet", "run", "-p", "Security/Identity/", "--no-launch-profile"] 

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 as prod

WORKDIR /app/
#COPY --from=Debug /out/ /app/
COPY --from=debug /identitywork/out /app/
RUN chmod +x /app/ 
CMD dotnet Identity.dll
